"""
build_data_js.py
-----------------
Reads data/telemetry.csv, data/crew.json, data/mission.json and
data/nasa-references.json and writes data/data.js, which embeds their
contents as plain JavaScript globals.

Why this exists:
Browsers block fetch()/XHR of local files when a page is opened directly
via file:// (double-clicked, no local server). To keep the prototype
"open index.html and it just works," data.js is loaded with a normal
<script> tag instead of being fetched, and app code reads from the
window.AHM_DATA object it defines. data/*.csv and data/*.json remain the
human-editable source of truth — re-run this script after editing them.

Run: python3 build_data_js.py
Output: ../data/data.js
"""

import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


def read_text(name):
    with open(os.path.join(DATA_DIR, name), "r") as f:
        return f.read()


def read_json(name):
    with open(os.path.join(DATA_DIR, name), "r") as f:
        return json.load(f)


def main():
    telemetry_csv = read_text("telemetry.csv")
    crew = read_json("crew.json")
    mission = read_json("mission.json")
    references = read_json("nasa-references.json")

    out = []
    out.append("// AUTO-GENERATED by tools/build_data_js.py — do not edit by hand.")
    out.append("// Edit data/telemetry.csv, data/crew.json, data/mission.json or")
    out.append("// data/nasa-references.json instead, then re-run that script.")
    out.append("window.AHM_DATA = {")
    out.append(f"  telemetryCsv: {json.dumps(telemetry_csv)},")
    out.append(f"  crew: {json.dumps(crew, indent=2)},")
    out.append(f"  mission: {json.dumps(mission, indent=2)},")
    out.append(f"  references: {json.dumps(references, indent=2)},")
    out.append("};")

    out_path = os.path.join(DATA_DIR, "data.js")
    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
