// Embeds data/*.csv + data/*.json into data/data.js (window.AHM_DATA) so index.html works from file://.
// Edit the source files in data/, then run: node tools/build-data.js
const fs = require('fs'), path = require('path');
const d = (f) => path.join(__dirname, '..', 'data', f);
const json = (f) => JSON.stringify(JSON.parse(fs.readFileSync(d(f), 'utf8')), null, 2);
const parts = [
  `telemetryCsv: ${JSON.stringify(fs.readFileSync(d('telemetry.csv'), 'utf8'))}`,
  ...[['crew'], ['mission'], ['events'], ['references', 'nasa-references'], ['modern', 'modern-monitoring']]
    .map(([k, f]) => `${k}: ${json((f || k) + '.json')}`),
];
fs.writeFileSync(d('data.js'),
  `// AUTO-GENERATED by tools/build-data.js — do not edit by hand; edit data/*.csv|json and re-run it.\nwindow.AHM_DATA = {\n  ${parts.join(',\n  ')},\n};\n`);
console.log('Wrote', d('data.js'));
